import Link from "next/link";

export const metadata = {
  title: "Terms of Service — Gherkin",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen flex flex-col bg-stone-50">
      <header className="px-8 py-6">
        <Link
          href="/"
          className="text-sm text-[#466353] hover:text-stone-700 transition-colors"
        >
          ← Back
        </Link>
      </header>

      <main className="flex-1 max-w-2xl mx-auto px-8 py-12 text-stone-700 leading-relaxed">
        <p className="text-xs uppercase tracking-widest text-[#466353] mb-4">
          Legal
        </p>
        <h1 className="text-3xl font-light text-stone-900 mb-2">
          Terms of Service
        </h1>
        <p className="text-xs text-[#466353] mb-12">
          Last updated: June 2025 &mdash;{" "}
          <span className="italic">
            Note: these terms have not been reviewed by a lawyer. They represent
            our genuine intent, but should not be treated as legal advice.
          </span>
        </p>

        <section className="mb-10">
          <h2 className="text-sm font-semibold uppercase tracking-widest text-[#466353] mb-4">
            What Gherkin is
          </h2>
          <p className="text-sm mb-3">
            Gherkin is a personal self-reflection tool. It helps you explore
            questions you&apos;ve never been asked, build a private gallery of
            your answers, and discover patterns in who you are over time.
          </p>
          <p className="text-sm">
            Gherkin is currently a demo project. By using it, you understand
            that it is not a finished commercial product and may change or
            become unavailable.
          </p>
        </section>

        <section className="mb-10">
          <h2 className="text-sm font-semibold uppercase tracking-widest text-[#466353] mb-4">
            Your account
          </h2>
          <div className="space-y-3 text-sm">
            <p>
              You must be at least 16 years old to create an account (the
              minimum age for consent under GDPR Article 8).
            </p>
            <p>
              You are responsible for keeping your login credentials secure. You
              are responsible for all activity that happens under your account.
            </p>
            <p>
              We may suspend or delete accounts that violate these terms, at our
              discretion.
            </p>
          </div>
        </section>

        <section className="mb-10">
          <h2 className="text-sm font-semibold uppercase tracking-widest text-[#466353] mb-4">
            Your content
          </h2>
          <div className="space-y-3 text-sm">
            <p>
              Your reflections are yours. You own them. We do not claim any
              rights over what you write.
            </p>
            <p>
              By writing a reflection, you grant us a limited licence to store
              it, generate a semantic embedding from it, and use those to power
              your personalised experience. We do not use your reflections to
              train AI models.
            </p>
            <p>
              You are responsible for what you write. Do not use Gherkin to
              store content that is illegal, harmful, or that violates
              others&apos; rights.
            </p>
          </div>
        </section>

        <section className="mb-10">
          <h2 className="text-sm font-semibold uppercase tracking-widest text-[#466353] mb-4">
            What we provide
          </h2>
          <div className="space-y-3 text-sm">
            <p>
              Gherkin is provided &ldquo;as is.&rdquo; We make no guarantees
              about uptime, availability, or fitness for any particular purpose.
            </p>
            <p>
              The AI-generated content in Gherkin (tone renderings, pattern
              summaries) is generated by language models. It may be inaccurate,
              incomplete, or surprising. It is offered for reflection and
              exploration, not as advice of any kind.
            </p>
            <p>
              Gherkin is not a mental health tool and is not a substitute for
              professional support.
            </p>
          </div>
        </section>

        <section className="mb-10">
          <h2 className="text-sm font-semibold uppercase tracking-widest text-[#466353] mb-4">
            Usage limits
          </h2>
          <p className="text-sm">
            To ensure fair access and manage costs, we apply rate limits: 20
            reflections per day, 50 card draws per day, and 5 pattern summaries
            per day. These limits may change.
          </p>
        </section>

        <section className="mb-10">
          <h2 className="text-sm font-semibold uppercase tracking-widest text-[#466353] mb-4">
            Termination
          </h2>
          <p className="text-sm">
            You can delete your account at any time. We may also terminate
            access to the service at any time. In either case, we will delete
            your data in line with our{" "}
            <Link
              href="/privacy"
              className="text-stone-900 underline underline-offset-2"
            >
              Privacy Policy
            </Link>
            .
          </p>
        </section>

        <section className="mb-10">
          <h2 className="text-sm font-semibold uppercase tracking-widest text-[#466353] mb-4">
            Governing law
          </h2>
          <p className="text-sm">
            These terms are governed by the laws of the Federal Republic of
            Germany. Any disputes will be resolved in the courts of Germany.
          </p>
        </section>

        <section className="mb-10">
          <h2 className="text-sm font-semibold uppercase tracking-widest text-[#466353] mb-4">
            Contact
          </h2>
          <p className="text-sm">
            Questions about these terms?{" "}
            <a
              href="mailto:lucysasvari@gmail.com"
              className="text-stone-900 underline underline-offset-2"
            >
              lucysasvari@gmail.com
            </a>
          </p>
        </section>
      </main>
    </div>
  );
}
